version: '3'
services:
  borgmatic:
    image: ghcr.io/tuetenk0pp/borg-rclone
    container_name: borgmatic
    env_file:
      - .env
      - .env.override
    volumes:
      - ${VOLUME_RCLONE_CONFIG}:/root/.config/rclone  # rclone config
